#include "common.h"


HKEY	hHKey[2] = {HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE}; 
LPCTSTR paszRuns[5] = {REG_PATH_RUN, REG_PATH_RUNONCE, REG_PATH_RUNONCEEX, REG_PATH_RUNSERVICES, REG_PATH_RUNSERVICESONCE};

DWORD	cchValue = MAX_VALUE_NAME; 
DWORD	cchData = MAX_PATH;
TCHAR	achValue[MAX_VALUE_NAME]; 
TCHAR	achData[MAX_PATH];
